# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Toborch/DELIVERY/JAM/EpitechJam2023

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Toborch/DELIVERY/JAM/EpitechJam2023

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Toborch/DELIVERY/JAM/EpitechJam2023/CMakeFiles /home/Toborch/DELIVERY/JAM/EpitechJam2023//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Toborch/DELIVERY/JAM/EpitechJam2023/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nerdSimulator

# Build rule for target.
nerdSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nerdSimulator
.PHONY : nerdSimulator

# fast build rule for target.
nerdSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/build
.PHONY : nerdSimulator/fast

src/animation/Animation.o: src/animation/Animation.cpp.o
.PHONY : src/animation/Animation.o

# target to build an object file
src/animation/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/animation/Animation.cpp.o
.PHONY : src/animation/Animation.cpp.o

src/animation/Animation.i: src/animation/Animation.cpp.i
.PHONY : src/animation/Animation.i

# target to preprocess a source file
src/animation/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/animation/Animation.cpp.i
.PHONY : src/animation/Animation.cpp.i

src/animation/Animation.s: src/animation/Animation.cpp.s
.PHONY : src/animation/Animation.s

# target to generate assembly for a file
src/animation/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/animation/Animation.cpp.s
.PHONY : src/animation/Animation.cpp.s

src/clock/Clock.o: src/clock/Clock.cpp.o
.PHONY : src/clock/Clock.o

# target to build an object file
src/clock/Clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/clock/Clock.cpp.o
.PHONY : src/clock/Clock.cpp.o

src/clock/Clock.i: src/clock/Clock.cpp.i
.PHONY : src/clock/Clock.i

# target to preprocess a source file
src/clock/Clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/clock/Clock.cpp.i
.PHONY : src/clock/Clock.cpp.i

src/clock/Clock.s: src/clock/Clock.cpp.s
.PHONY : src/clock/Clock.s

# target to generate assembly for a file
src/clock/Clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/clock/Clock.cpp.s
.PHONY : src/clock/Clock.cpp.s

src/cursor/Cursor.o: src/cursor/Cursor.cpp.o
.PHONY : src/cursor/Cursor.o

# target to build an object file
src/cursor/Cursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/cursor/Cursor.cpp.o
.PHONY : src/cursor/Cursor.cpp.o

src/cursor/Cursor.i: src/cursor/Cursor.cpp.i
.PHONY : src/cursor/Cursor.i

# target to preprocess a source file
src/cursor/Cursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/cursor/Cursor.cpp.i
.PHONY : src/cursor/Cursor.cpp.i

src/cursor/Cursor.s: src/cursor/Cursor.cpp.s
.PHONY : src/cursor/Cursor.s

# target to generate assembly for a file
src/cursor/Cursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/cursor/Cursor.cpp.s
.PHONY : src/cursor/Cursor.cpp.s

src/drawable/box/SatBox.o: src/drawable/box/SatBox.cpp.o
.PHONY : src/drawable/box/SatBox.o

# target to build an object file
src/drawable/box/SatBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/drawable/box/SatBox.cpp.o
.PHONY : src/drawable/box/SatBox.cpp.o

src/drawable/box/SatBox.i: src/drawable/box/SatBox.cpp.i
.PHONY : src/drawable/box/SatBox.i

# target to preprocess a source file
src/drawable/box/SatBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/drawable/box/SatBox.cpp.i
.PHONY : src/drawable/box/SatBox.cpp.i

src/drawable/box/SatBox.s: src/drawable/box/SatBox.cpp.s
.PHONY : src/drawable/box/SatBox.s

# target to generate assembly for a file
src/drawable/box/SatBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/drawable/box/SatBox.cpp.s
.PHONY : src/drawable/box/SatBox.cpp.s

src/drawable/rectangle/Rectangle.o: src/drawable/rectangle/Rectangle.cpp.o
.PHONY : src/drawable/rectangle/Rectangle.o

# target to build an object file
src/drawable/rectangle/Rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/drawable/rectangle/Rectangle.cpp.o
.PHONY : src/drawable/rectangle/Rectangle.cpp.o

src/drawable/rectangle/Rectangle.i: src/drawable/rectangle/Rectangle.cpp.i
.PHONY : src/drawable/rectangle/Rectangle.i

# target to preprocess a source file
src/drawable/rectangle/Rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/drawable/rectangle/Rectangle.cpp.i
.PHONY : src/drawable/rectangle/Rectangle.cpp.i

src/drawable/rectangle/Rectangle.s: src/drawable/rectangle/Rectangle.cpp.s
.PHONY : src/drawable/rectangle/Rectangle.s

# target to generate assembly for a file
src/drawable/rectangle/Rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/drawable/rectangle/Rectangle.cpp.s
.PHONY : src/drawable/rectangle/Rectangle.cpp.s

src/engine/Engine.o: src/engine/Engine.cpp.o
.PHONY : src/engine/Engine.o

# target to build an object file
src/engine/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/engine/Engine.cpp.o
.PHONY : src/engine/Engine.cpp.o

src/engine/Engine.i: src/engine/Engine.cpp.i
.PHONY : src/engine/Engine.i

# target to preprocess a source file
src/engine/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/engine/Engine.cpp.i
.PHONY : src/engine/Engine.cpp.i

src/engine/Engine.s: src/engine/Engine.cpp.s
.PHONY : src/engine/Engine.s

# target to generate assembly for a file
src/engine/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/engine/Engine.cpp.s
.PHONY : src/engine/Engine.cpp.s

src/entity/AEntity.o: src/entity/AEntity.cpp.o
.PHONY : src/entity/AEntity.o

# target to build an object file
src/entity/AEntity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/entity/AEntity.cpp.o
.PHONY : src/entity/AEntity.cpp.o

src/entity/AEntity.i: src/entity/AEntity.cpp.i
.PHONY : src/entity/AEntity.i

# target to preprocess a source file
src/entity/AEntity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/entity/AEntity.cpp.i
.PHONY : src/entity/AEntity.cpp.i

src/entity/AEntity.s: src/entity/AEntity.cpp.s
.PHONY : src/entity/AEntity.s

# target to generate assembly for a file
src/entity/AEntity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/entity/AEntity.cpp.s
.PHONY : src/entity/AEntity.cpp.s

src/entity/controller/Controller.o: src/entity/controller/Controller.cpp.o
.PHONY : src/entity/controller/Controller.o

# target to build an object file
src/entity/controller/Controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/entity/controller/Controller.cpp.o
.PHONY : src/entity/controller/Controller.cpp.o

src/entity/controller/Controller.i: src/entity/controller/Controller.cpp.i
.PHONY : src/entity/controller/Controller.i

# target to preprocess a source file
src/entity/controller/Controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/entity/controller/Controller.cpp.i
.PHONY : src/entity/controller/Controller.cpp.i

src/entity/controller/Controller.s: src/entity/controller/Controller.cpp.s
.PHONY : src/entity/controller/Controller.s

# target to generate assembly for a file
src/entity/controller/Controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/entity/controller/Controller.cpp.s
.PHONY : src/entity/controller/Controller.cpp.s

src/helper/info/info.o: src/helper/info/info.cpp.o
.PHONY : src/helper/info/info.o

# target to build an object file
src/helper/info/info.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/info/info.cpp.o
.PHONY : src/helper/info/info.cpp.o

src/helper/info/info.i: src/helper/info/info.cpp.i
.PHONY : src/helper/info/info.i

# target to preprocess a source file
src/helper/info/info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/info/info.cpp.i
.PHONY : src/helper/info/info.cpp.i

src/helper/info/info.s: src/helper/info/info.cpp.s
.PHONY : src/helper/info/info.s

# target to generate assembly for a file
src/helper/info/info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/info/info.cpp.s
.PHONY : src/helper/info/info.cpp.s

src/helper/math/math.o: src/helper/math/math.cpp.o
.PHONY : src/helper/math/math.o

# target to build an object file
src/helper/math/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/math/math.cpp.o
.PHONY : src/helper/math/math.cpp.o

src/helper/math/math.i: src/helper/math/math.cpp.i
.PHONY : src/helper/math/math.i

# target to preprocess a source file
src/helper/math/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/math/math.cpp.i
.PHONY : src/helper/math/math.cpp.i

src/helper/math/math.s: src/helper/math/math.cpp.s
.PHONY : src/helper/math/math.s

# target to generate assembly for a file
src/helper/math/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/math/math.cpp.s
.PHONY : src/helper/math/math.cpp.s

src/helper/number_generator/numberGenerator.o: src/helper/number_generator/numberGenerator.cpp.o
.PHONY : src/helper/number_generator/numberGenerator.o

# target to build an object file
src/helper/number_generator/numberGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/number_generator/numberGenerator.cpp.o
.PHONY : src/helper/number_generator/numberGenerator.cpp.o

src/helper/number_generator/numberGenerator.i: src/helper/number_generator/numberGenerator.cpp.i
.PHONY : src/helper/number_generator/numberGenerator.i

# target to preprocess a source file
src/helper/number_generator/numberGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/number_generator/numberGenerator.cpp.i
.PHONY : src/helper/number_generator/numberGenerator.cpp.i

src/helper/number_generator/numberGenerator.s: src/helper/number_generator/numberGenerator.cpp.s
.PHONY : src/helper/number_generator/numberGenerator.s

# target to generate assembly for a file
src/helper/number_generator/numberGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/helper/number_generator/numberGenerator.cpp.s
.PHONY : src/helper/number_generator/numberGenerator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/resource_manager/ResourceManager.o: src/resource_manager/ResourceManager.cpp.o
.PHONY : src/resource_manager/ResourceManager.o

# target to build an object file
src/resource_manager/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/resource_manager/ResourceManager.cpp.o
.PHONY : src/resource_manager/ResourceManager.cpp.o

src/resource_manager/ResourceManager.i: src/resource_manager/ResourceManager.cpp.i
.PHONY : src/resource_manager/ResourceManager.i

# target to preprocess a source file
src/resource_manager/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/resource_manager/ResourceManager.cpp.i
.PHONY : src/resource_manager/ResourceManager.cpp.i

src/resource_manager/ResourceManager.s: src/resource_manager/ResourceManager.cpp.s
.PHONY : src/resource_manager/ResourceManager.s

# target to generate assembly for a file
src/resource_manager/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/resource_manager/ResourceManager.cpp.s
.PHONY : src/resource_manager/ResourceManager.cpp.s

src/scene/menu/MenuScene.o: src/scene/menu/MenuScene.cpp.o
.PHONY : src/scene/menu/MenuScene.o

# target to build an object file
src/scene/menu/MenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/menu/MenuScene.cpp.o
.PHONY : src/scene/menu/MenuScene.cpp.o

src/scene/menu/MenuScene.i: src/scene/menu/MenuScene.cpp.i
.PHONY : src/scene/menu/MenuScene.i

# target to preprocess a source file
src/scene/menu/MenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/menu/MenuScene.cpp.i
.PHONY : src/scene/menu/MenuScene.cpp.i

src/scene/menu/MenuScene.s: src/scene/menu/MenuScene.cpp.s
.PHONY : src/scene/menu/MenuScene.s

# target to generate assembly for a file
src/scene/menu/MenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/menu/MenuScene.cpp.s
.PHONY : src/scene/menu/MenuScene.cpp.s

src/scene/room/RoomScene.o: src/scene/room/RoomScene.cpp.o
.PHONY : src/scene/room/RoomScene.o

# target to build an object file
src/scene/room/RoomScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/room/RoomScene.cpp.o
.PHONY : src/scene/room/RoomScene.cpp.o

src/scene/room/RoomScene.i: src/scene/room/RoomScene.cpp.i
.PHONY : src/scene/room/RoomScene.i

# target to preprocess a source file
src/scene/room/RoomScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/room/RoomScene.cpp.i
.PHONY : src/scene/room/RoomScene.cpp.i

src/scene/room/RoomScene.s: src/scene/room/RoomScene.cpp.s
.PHONY : src/scene/room/RoomScene.s

# target to generate assembly for a file
src/scene/room/RoomScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/room/RoomScene.cpp.s
.PHONY : src/scene/room/RoomScene.cpp.s

src/scene/scene_manager/SceneManager.o: src/scene/scene_manager/SceneManager.cpp.o
.PHONY : src/scene/scene_manager/SceneManager.o

# target to build an object file
src/scene/scene_manager/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/scene_manager/SceneManager.cpp.o
.PHONY : src/scene/scene_manager/SceneManager.cpp.o

src/scene/scene_manager/SceneManager.i: src/scene/scene_manager/SceneManager.cpp.i
.PHONY : src/scene/scene_manager/SceneManager.i

# target to preprocess a source file
src/scene/scene_manager/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/scene_manager/SceneManager.cpp.i
.PHONY : src/scene/scene_manager/SceneManager.cpp.i

src/scene/scene_manager/SceneManager.s: src/scene/scene_manager/SceneManager.cpp.s
.PHONY : src/scene/scene_manager/SceneManager.s

# target to generate assembly for a file
src/scene/scene_manager/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/scene_manager/SceneManager.cpp.s
.PHONY : src/scene/scene_manager/SceneManager.cpp.s

src/scene/settings/SettingsScene.o: src/scene/settings/SettingsScene.cpp.o
.PHONY : src/scene/settings/SettingsScene.o

# target to build an object file
src/scene/settings/SettingsScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/settings/SettingsScene.cpp.o
.PHONY : src/scene/settings/SettingsScene.cpp.o

src/scene/settings/SettingsScene.i: src/scene/settings/SettingsScene.cpp.i
.PHONY : src/scene/settings/SettingsScene.i

# target to preprocess a source file
src/scene/settings/SettingsScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/settings/SettingsScene.cpp.i
.PHONY : src/scene/settings/SettingsScene.cpp.i

src/scene/settings/SettingsScene.s: src/scene/settings/SettingsScene.cpp.s
.PHONY : src/scene/settings/SettingsScene.s

# target to generate assembly for a file
src/scene/settings/SettingsScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/scene/settings/SettingsScene.cpp.s
.PHONY : src/scene/settings/SettingsScene.cpp.s

src/ui/Widget.o: src/ui/Widget.cpp.o
.PHONY : src/ui/Widget.o

# target to build an object file
src/ui/Widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/Widget.cpp.o
.PHONY : src/ui/Widget.cpp.o

src/ui/Widget.i: src/ui/Widget.cpp.i
.PHONY : src/ui/Widget.i

# target to preprocess a source file
src/ui/Widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/Widget.cpp.i
.PHONY : src/ui/Widget.cpp.i

src/ui/Widget.s: src/ui/Widget.cpp.s
.PHONY : src/ui/Widget.s

# target to generate assembly for a file
src/ui/Widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/Widget.cpp.s
.PHONY : src/ui/Widget.cpp.s

src/ui/button/Button.o: src/ui/button/Button.cpp.o
.PHONY : src/ui/button/Button.o

# target to build an object file
src/ui/button/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/button/Button.cpp.o
.PHONY : src/ui/button/Button.cpp.o

src/ui/button/Button.i: src/ui/button/Button.cpp.i
.PHONY : src/ui/button/Button.i

# target to preprocess a source file
src/ui/button/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/button/Button.cpp.i
.PHONY : src/ui/button/Button.cpp.i

src/ui/button/Button.s: src/ui/button/Button.cpp.s
.PHONY : src/ui/button/Button.s

# target to generate assembly for a file
src/ui/button/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/button/Button.cpp.s
.PHONY : src/ui/button/Button.cpp.s

src/ui/slider/Slider.o: src/ui/slider/Slider.cpp.o
.PHONY : src/ui/slider/Slider.o

# target to build an object file
src/ui/slider/Slider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/slider/Slider.cpp.o
.PHONY : src/ui/slider/Slider.cpp.o

src/ui/slider/Slider.i: src/ui/slider/Slider.cpp.i
.PHONY : src/ui/slider/Slider.i

# target to preprocess a source file
src/ui/slider/Slider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/slider/Slider.cpp.i
.PHONY : src/ui/slider/Slider.cpp.i

src/ui/slider/Slider.s: src/ui/slider/Slider.cpp.s
.PHONY : src/ui/slider/Slider.s

# target to generate assembly for a file
src/ui/slider/Slider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/slider/Slider.cpp.s
.PHONY : src/ui/slider/Slider.cpp.s

src/ui/text/UIText.o: src/ui/text/UIText.cpp.o
.PHONY : src/ui/text/UIText.o

# target to build an object file
src/ui/text/UIText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/text/UIText.cpp.o
.PHONY : src/ui/text/UIText.cpp.o

src/ui/text/UIText.i: src/ui/text/UIText.cpp.i
.PHONY : src/ui/text/UIText.i

# target to preprocess a source file
src/ui/text/UIText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/text/UIText.cpp.i
.PHONY : src/ui/text/UIText.cpp.i

src/ui/text/UIText.s: src/ui/text/UIText.cpp.s
.PHONY : src/ui/text/UIText.s

# target to generate assembly for a file
src/ui/text/UIText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nerdSimulator.dir/build.make CMakeFiles/nerdSimulator.dir/src/ui/text/UIText.cpp.s
.PHONY : src/ui/text/UIText.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nerdSimulator"
	@echo "... src/animation/Animation.o"
	@echo "... src/animation/Animation.i"
	@echo "... src/animation/Animation.s"
	@echo "... src/clock/Clock.o"
	@echo "... src/clock/Clock.i"
	@echo "... src/clock/Clock.s"
	@echo "... src/cursor/Cursor.o"
	@echo "... src/cursor/Cursor.i"
	@echo "... src/cursor/Cursor.s"
	@echo "... src/drawable/box/SatBox.o"
	@echo "... src/drawable/box/SatBox.i"
	@echo "... src/drawable/box/SatBox.s"
	@echo "... src/drawable/rectangle/Rectangle.o"
	@echo "... src/drawable/rectangle/Rectangle.i"
	@echo "... src/drawable/rectangle/Rectangle.s"
	@echo "... src/engine/Engine.o"
	@echo "... src/engine/Engine.i"
	@echo "... src/engine/Engine.s"
	@echo "... src/entity/AEntity.o"
	@echo "... src/entity/AEntity.i"
	@echo "... src/entity/AEntity.s"
	@echo "... src/entity/controller/Controller.o"
	@echo "... src/entity/controller/Controller.i"
	@echo "... src/entity/controller/Controller.s"
	@echo "... src/helper/info/info.o"
	@echo "... src/helper/info/info.i"
	@echo "... src/helper/info/info.s"
	@echo "... src/helper/math/math.o"
	@echo "... src/helper/math/math.i"
	@echo "... src/helper/math/math.s"
	@echo "... src/helper/number_generator/numberGenerator.o"
	@echo "... src/helper/number_generator/numberGenerator.i"
	@echo "... src/helper/number_generator/numberGenerator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/resource_manager/ResourceManager.o"
	@echo "... src/resource_manager/ResourceManager.i"
	@echo "... src/resource_manager/ResourceManager.s"
	@echo "... src/scene/menu/MenuScene.o"
	@echo "... src/scene/menu/MenuScene.i"
	@echo "... src/scene/menu/MenuScene.s"
	@echo "... src/scene/room/RoomScene.o"
	@echo "... src/scene/room/RoomScene.i"
	@echo "... src/scene/room/RoomScene.s"
	@echo "... src/scene/scene_manager/SceneManager.o"
	@echo "... src/scene/scene_manager/SceneManager.i"
	@echo "... src/scene/scene_manager/SceneManager.s"
	@echo "... src/scene/settings/SettingsScene.o"
	@echo "... src/scene/settings/SettingsScene.i"
	@echo "... src/scene/settings/SettingsScene.s"
	@echo "... src/ui/Widget.o"
	@echo "... src/ui/Widget.i"
	@echo "... src/ui/Widget.s"
	@echo "... src/ui/button/Button.o"
	@echo "... src/ui/button/Button.i"
	@echo "... src/ui/button/Button.s"
	@echo "... src/ui/slider/Slider.o"
	@echo "... src/ui/slider/Slider.i"
	@echo "... src/ui/slider/Slider.s"
	@echo "... src/ui/text/UIText.o"
	@echo "... src/ui/text/UIText.i"
	@echo "... src/ui/text/UIText.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

